kind: ConfigMap
apiVersion: v1 
metadata:
  name: server-conf
  namespace: dev
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.13:3306/gdpr?autoReconnect=true&verifyServerCertificate=false&useSSL=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root