apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-app-server
  namespace: dev
  labels:
    app: med-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: med-app-server
  template:
    metadata:
      labels:
        app: med-app-server
    spec:
      volumes:
      - name: server-conf
        configMap:
          name: server-conf
      containers:
      - name: med-app-server
        image: med_proj_app_server
        envFrom:
        - configMapRef:
            name: server-conf
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8089
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"