apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-app-server
  namespace: dev
  labels:
    app: med-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: med-app-server
  template:
    metadata:
      labels:
        app: med-app-server
        #tier: backend
    spec:
      containers:
      - name: med-app-server
        image: med_proj_app_server
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://192.168.1.13:3306/gdpr?autoReconnect=true&verifyServerCertificate=false&useSSL=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8089
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
      # - name: med-app-db
      #   image: mysql:8.0.17
      #   env:
      #     - name: MYSQL_ROOT_PASSWORD
      #       value: root
      #   ports:
      #     - containerPort: 3306
      #   imagePullPolicy: IfNotPresent
      #   resources:
      #     requests:
      #       memory: "1Gi"
      #       cpu: "0.5"
      #     limits:
      #       memory: "2Gi"
      #       cpu: "1"