apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-app-deployment
  labels:
    app: med-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: med-app
  template:
    metadata:
      labels:
        app: med-app
    spec:
      containers:
      - name: med-app-client
        image: med_proj_app_client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
      - name: med-app-server
        image: med_proj_app_server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
      - name: med-app-db
        image: mysql:8.0.17
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"