apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-app-db
  namespace: dev
  labels:
    app: med-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: med-app-db
  template:
    metadata:
      labels:
        app: med-app-db
    spec:
      containers:
      - name: med-app-db
        image: mysql:8.0.17
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        ports:
          - containerPort: 3306
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"