version: '3.7'
services:
  app-server:
    build: 
      context: server  # Use an image built from the specified dockerfile in the 'server' directory
      dockerfile: Dockerfile
    restart: always
    container_name: app_server
    ports:
     - "8089:8089"
    restart: always
    depends_on: 
      - db
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gdpr?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gdpr?autoReconnect=true&verifyServerCertificate=false&useSSL=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  db:
    image: mysql:8.0.17
    restart: always
    container_name: mysql
    environment:
      #MYSQL_DATABASE: gdpr
      MYSQL_ROOT_PASSWORD: root
    command: --lower_case_table_names=1
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend

  app-client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    container_name: client_server
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: