version: '3'
services:
  app_server:
    build: 
      context: server
      dockerfile: Dockerfile
    restart: always
    container_name: app_server
    ports:
     - "8089:8089"
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gdpr?autoReconnect=true&verifyServerCertificate=false&useSSL=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend
      - frontend
  db:
    image: mysql:8.0.17
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --lower_case_table_names=1
    volumes:
      - /home/db-data:/var/lib/mysql
    networks:
      - backend
  app_client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    container_name: client_server
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app_server
    networks:
      - frontend
volumes:
  db-data:
networks:
  backend:
  frontend: