kind: Service
apiVersion: v1
metadata:
  name: med-app-client-service
  namespace: dev
spec:
  selector:
    app: med-app-client
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort